import React from 'react';
import { TouchableOpacity, Text, StyleSheet, Alert } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Ionicons } from '@expo/vector-icons';
import Colors from '../../theme/colors';

interface PickedFile {
  uri: string;
  name: string;
  mimeType?: string;
}

interface DownloadReportProps {
  score: number | null;
  file1: PickedFile | null;
  file2: PickedFile | null;
}

export default function DownloadReport({ score, file1, file2 }: DownloadReportProps) {
  if (score === null) return null;

  let status = 'Low Similarity';
  if (score >= 80)      status = 'High Similarity';
  else if (score >= 50) status = 'Moderate Similarity';

  const downloadPDF = async () => {
    try {
      const html = `
        <html>
          <body style="font-family: Arial, sans-serif; padding: 32px; color: #1E293B;">
            <h1 style="color: #2563EB;">AI Similarity Report</h1>
            <hr/>
            <table style="width:100%; border-collapse:collapse; margin-top:20px;">
              <tr><th style="text-align:left; padding:8px; background:#EFF6FF;">Assignment 1</th><td style="padding:8px;">${file1?.name ?? '—'}</td></tr>
              <tr><th style="text-align:left; padding:8px;">Assignment 2</th><td style="padding:8px;">${file2?.name ?? '—'}</td></tr>
              <tr><th style="text-align:left; padding:8px; background:#EFF6FF;">Similarity</th><td style="padding:8px;">${score}%</td></tr>
              <tr><th style="text-align:left; padding:8px;">Status</th><td style="padding:8px;">${status}</td></tr>
            </table>
            <p style="margin-top:40px; color:#94A3B8; font-size:12px;">Generated by Student ERP AI Similarity Checker</p>
          </body>
        </html>`;

      const { uri } = await Print.printToFileAsync({ html });

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Download Similarity Report',
        });
      } else {
        Alert.alert('Saved', `Report saved to: ${uri}`);
      }
    } catch (err) {
      console.error(err);
      Alert.alert('Error', 'Unable to generate report.');
    }
  };

  return (
    <TouchableOpacity style={styles.btn} onPress={downloadPDF}>
      <Ionicons name="download-outline" size={18} color={Colors.white} />
      <Text style={styles.btnText}>Download Report (PDF)</Text>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  btn: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    backgroundColor: Colors.success, borderRadius: 10,
    paddingVertical: 13, paddingHorizontal: 18,
    marginTop: 14, alignSelf: 'flex-start',
  },
  btnText: { color: Colors.white, fontWeight: '700', fontSize: 14 },
});
